[package]
name = "rustzx"
version = "0.8.0"
authors = ["Vladislav Nikonov <pacmancoder@gmail.com>"]
publish = false
description = "ZX Spectum emulator"
repository = "https://github.com/pacmancoder/rustzx"
readme = "README.md"
keywords = ["emulator", "game", "z80"]
license = "MIT"

# [package.metadata.deb]
# maintainer = "Vladislav Nikonov <pacmancoder@gmail.com>"
# copyright = "2016, Vladislav Nikonov <pacmancoder@gmail.com>"
# license_file = ["LICENSE.md", "3"]
# depends = "$auto"
# extended_description = """\
# ZX Spectrum 48K emulator written in Rust."""
# section = "games"
# priority = "optional"
# assets = [
    # ["target/release/rustzx", "usr/bin/rustzx", "755"],
# ]

[dependencies]
time = "0.1"
glium = "0.13"
lazy_static = "0.2.1"
clap = "2.5.2"
portaudio = "0.6.4"
cgmath ="0.10.0"
