[package]
name = "rustzx"
version = "0.8.7"
authors = ["Vladislav Nikonov <pacmancoder@gmail.com>"]
publish = false
description = "ZX Spectum emulator"
repository = "https://github.com/pacmancoder/rustzx"
readme = "README.md"
keywords = ["emulator", "game", "z80"]
license = "MIT"

[dependencies]
time = "0.1"
glium = "0.13"
lazy_static = "0.2"
clap = "2.9"
portaudio = "0.6"
cgmath ="0.10"
num = "0.1"

ayumi = { git = "https://github.com/pacmancoder/rust-ayumi.git"}
